# Generated by Django 4.2.4 on 2023-10-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='ESPAR',
        ),
    ]
